require('dotenv').config();
const bcrypt = require('bcryptjs');
const { sequelize, User, Product } = require('../models');

async function seed() {
  await sequelize.sync({ force: true });
  console.log('✅ Tables created');

  const hash = (pw) => bcrypt.hashSync(pw, 10);

  await User.bulkCreate([
    { name: 'Admin User',     email: 'admin@beauty.com',     password: hash('admin123'),     role: 'admin' },
    { name: 'Logistics User', email: 'logistics@beauty.com', password: hash('logistics123'), role: 'logistics' },
    { name: 'Sara Cohen',     email: 'sara@example.com',     password: hash('sara123'),      role: 'customer', skinType: 'dry', concern: 'wrinkles' },
  ]);
  console.log('✅ Users seeded');

await Product.bulkCreate([
    { name: "Velvet Hydrating Cleanser", category: "Cleanser", description: "A rich, cream-to-foam formula infused with Hyaluronic Acid. Designed for dry skin to restore moisture while gently removing impurities.", skinType: "dry", price: 22, imageUrl: "https://i.postimg.cc/Ghh7rwJD/Whats-App-Image-2026-06-01-at-19-47-56-(1).jpg", stock: 50 },
    { name: "Clarifying Tea Tree Wash", category: "Cleanser", description: "A potent, oil-free gel cleanser featuring Tea Tree extract. Targets acne-prone skin by deep-cleaning pores and regulating excess sebum.", skinType: "oily", price: 27, imageUrl: "https://i.postimg.cc/hGfRGQL9/Whats-App-Image-2026-06-01-at-19-47-56.jpg", stock: 50 },
    { name: "Soothing Rose Micellar Water", category: "Cleanser", description: "An ultra-gentle, alcohol-free cleanser enriched with Damask Rose water. Ideal for sensitive skin to calm redness and remove makeup without irritation.", skinType: "sensitive", price: 19, imageUrl: "https://i.postimg.cc/6347C3XK/Whats-App-Image-2026-06-01-at-19-47-57.jpg", stock: 50 },
    { name: "Balanced Harmony Foam", category: "Cleanser", description: "A pH-balanced daily cleanser perfect for combination skin. It effectively balances T-zone oiliness while providing hydration to drier areas of the face.", skinType: "combination", price: 15, imageUrl: "https://i.postimg.cc/zGDV0prF/Whats-App-Image-2026-06-01-at-19-47-57-(1).jpg", stock: 50 },
    { name: "Radiant Enzyme Cleansing Powder", category: "Cleanser", description: "A sophisticated brightening powder that activates with water to create a soft lather. Ideal for mature skin seeking exfoliation and a smoother, younger texture.", skinType: "mature", price: 16, imageUrl: "https://i.postimg.cc/wxhMznxf/Whats-App-Image-2026-06-01-at-19-47-57-(2).jpg", stock: 50 },
    { name: "Triple-Action Balancing Emulsion", category: "Moisturizer", description: "A hybrid moisturizer that provides light hydration to dry zones while controlling shine in the T-zone. Perfectly balanced for combination complexions.", skinType: "combination", price: 30, imageUrl: "https://i.postimg.cc/zGkP1z4G/Whats-App-Image-2026-06-01-at-19-50-21-(2).jpg", stock: 50 },
    { name: "Luminous Peptide Cream", category: "Moisturizer", description: "A luxurious anti-aging moisturizer packed with peptides. Firms skin, boosts elasticity, and smooths fine lines for a youthful radiance.", skinType: "mature", price: 24, imageUrl: "https://i.postimg.cc/vZDG4KM6/Whats-App-Image-2026-06-01-at-19-50-21-(1).jpg", stock: 50 },
    { name: "Hydra-Burst Aqua Gel", category: "Moisturizer", description: "An ultra-lightweight, oil-free gel moisturizer. Infused with marine minerals to provide deep, refreshing hydration for oily skin without clogging pores.", skinType: "oily", price: 26, imageUrl: "https://i.postimg.cc/7PV4m4Zk/Whats-App-Image-2026-06-01-at-19-50-21.jpg", stock: 50 },
    { name: "Velvet Barrier Cream", category: "Moisturizer", description: "A rich, protective cream formulated with ceramides. Designed to soothe and repair dry, compromised skin barriers while locking in moisture.", skinType: "dry", price: 26, imageUrl: "https://i.postimg.cc/Ss40f10m/Whats-App-Image-2026-06-01-at-19-50-21-(1).jpg", stock: 50 },
    { name: "Calming Centella Balm", category: "Moisturizer", description: "A gentle, nourishing balm centered on Centella Asiatica. Perfect for sensitive skin to diminish redness and provide immediate comfort.", skinType: "sensitive", price: 25, imageUrl: "https://i.postimg.cc/L47DdYXk/Whats-App-Image-2026-06-01-at-19-50-22.jpg", stock: 50 },
    { name: "Gentle Soothing Cica Serum", category: "Serum", description: "Formulated with concentrated Centella Asiatica to soothe reactive, sensitive skin. Reduces redness and strengthens the skin barrier against environmental stressors.", skinType: "sensitive", price: 30, imageUrl: "https://i.postimg.cc/Pr9xhhs2/Whats-App-Image-2026-06-01-at-19-43-43-(1).jpg", stock: 50 },
    { name: "Retinol Renewal Night Serum", category: "Serum", description: "A powerful nighttime treatment with encapsulated retinol. Encourages cell turnover to soften deep wrinkles and rejuvenate mature skin overnight.", skinType: "mature", price: 31, imageUrl: "https://i.postimg.cc/N025TSgT/Whats-App-Image-2026-06-01-at-19-43-43.jpg", stock: 50 },
    { name: "Radiance Vitamin C Serum", category: "Serum", description: "A high-potency serum that brightens dull complexions. Packed with antioxidants to combat dark spots and provide a natural, healthy glow.", skinType: "all", price: 37, imageUrl: "https://i.postimg.cc/BbDqnPG8/Whats-App-Image-2026-06-01-at-19-43-43-(2).jpg", stock: 50 },
    { name: "Hyaluronic Intense Hydration", category: "Serum", description: "A pure, multi-molecular weight hyaluronic acid serum. Delivers intense moisture deep into the skin layers to plump and hydrate dry, dehydrated complexions.", skinType: "dry", price: 42, imageUrl: "https://i.postimg.cc/6QdLnYL0/Whats-App-Image-2026-06-01-at-21-52-52-(1).jpg", stock: 50 },
    { name: "Clarifying BHA Pore Minimizer", category: "Serum", description: "An active serum with 2% BHA to target stubborn blemishes and clogged pores. Perfect for oily, congested skin aiming for a matte and refined texture.", skinType: "oily", price: 68, imageUrl: "https://i.postimg.cc/dVC8c4Xk/Whats-App-Image-2026-06-01-at-21-53-36.jpg", stock: 50 },
    { name: "Deep Pore Charcoal Mask", category: "Mask & Pad", description: "A detoxifying clay mask infused with activated charcoal. Pulls out deep-seated impurities and absorbs excess oil, leaving skin clarified and matte.", skinType: "oily", price: 12, imageUrl: "https://i.postimg.cc/cLdXTqC2/Whats-App-Image-2026-06-01-at-19-56-52.jpg", stock: 50 },
    { name: "Hydra-Soak Overnight Mask", category: "Mask & Pad", description: "A sleeping mask that provides an intense moisture infusion. Rich in botanicals to soothe dry, tired skin and restore a supple texture by morning.", skinType: "dry", price: 15, imageUrl: "https://i.postimg.cc/PJmQzKjh/Whats-App-Image-2026-06-01-at-19-56-52-(1).jpg", stock: 50 },
    { name: "Calming Cica Toner Pads", category: "Mask & Pad", description: "Pre-soaked pads with Centella Asiatica for immediate soothing. Perfect for sensitive skin to swipe away redness and provide instant cooling relief.", skinType: "sensitive", price: 19, imageUrl: "https://i.postimg.cc/brjQJbtJ/Whats-App-Image-2026-06-01-at-19-56-52.jpg", stock: 50 },
    { name: "Firming Bio-Cellulose Sheet Mask", category: "Mask & Pad", description: "A high-performance sheet mask with collagen-boosting ingredients. Designed to lift and firm mature skin, reducing the appearance of fatigue.", skinType: "mature", price: 22, imageUrl: "https://i.postimg.cc/25sWcvTV/Whats-App-Image-2026-06-01-at-19-56-52-(1).jpg", stock: 50 },
    { name: "Dual-Action Exfoliating Pads", category: "Mask & Pad", description: "Textured pads with gentle AHAs for combination skin. The rough side exfoliates the T-zone, while the soft side hydrates drier cheeks.", skinType: "combination", price: 25, imageUrl: "https://i.postimg.cc/sg1Z3KND/Whats-App-Image-2026-06-01-at-19-56-52-(2).jpg", stock: 50 },
    { name: "Botanical Balancing Toner", category: "Toner & Mist", description: "A soothing, alcohol-free toner infused with Witch Hazel and Chamomile. Perfect for combination skin to tighten pores and maintain a healthy moisture balance.", skinType: "combination", price: 32, imageUrl: "https://i.postimg.cc/2yM3yNJQ/Whats-App-Image-2026-06-01-at-22-18-54.jpg", stock: 50 },
    { name: "Hydrating Rose Water Mist", category: "Toner & Mist", description: "A refreshing facial mist crafted from organic Damask Rose. Provides a burst of hydration to dry, thirsty skin throughout the day for a dewy look.", skinType: "dry", price: 28, imageUrl: "https://i.postimg.cc/LX4J0TLz/Whats-App-Image-2026-06-01-at-22-17-54-(5).jpg", stock: 50 },
    { name: "Clarifying Salicylic Toner", category: "Toner & Mist", description: "A potent, refining toner designed to clear excess oil and prevent breakouts. Ideal for oily skin to achieve a smooth, shine-free complexion.", skinType: "oily", price: 30, imageUrl: "https://i.postimg.cc/Sx8YXjmK/Whats-App-Image-2026-06-01-at-22-17-54-(4).jpg", stock: 50 },
    { name: "Sensitive Cica Calming Mist", category: "Toner & Mist", description: "An ultra-fine mist formulated with Centella Asiatica to instantly calm redness and soothe reactive, sensitive skin with a cooling sensation.", skinType: "sensitive", price: 35, imageUrl: "https://i.postimg.cc/NGJHSWdN/Whats-App-Image-2026-06-01-at-22-17-54-(3).jpg", stock: 50 },
    { name: "Youth-Restoring Essence Mist", category: "Toner & Mist", description: "A luxurious, anti-aging treatment mist. Packed with antioxidants and peptides to revitalize mature skin and maintain firmness during the day.", skinType: "mature", price: 40, imageUrl: "https://i.postimg.cc/dVC8c4Xk/Whats-App-Image-2026-06-01-at-21-53-36.jpg", stock: 50 },
    { name: "Invisible Shield SPF 50", category: "Sunscreen", description: "A lightweight, broad-spectrum sunscreen that leaves zero white cast. Perfect for all skin types for daily invisible protection.", skinType: "all", price: 55, imageUrl: "https://i.postimg.cc/y69MbH63/Whats-App-Image-2026-06-01-at-20-01-15-(4).jpg", stock: 50 },
    { name: "Matte-Finish Oil-Control SPF", category: "Sunscreen", description: "A shine-free sunscreen specifically for oily skin. Absorbs excess sebum throughout the day while providing robust sun protection.", skinType: "oily", price: 52, imageUrl: "https://i.postimg.cc/HkBD99WC/Whats-App-Image-2026-06-01-at-20-01-15-(3).jpg", stock: 50 },
    { name: "Moisturizing Sun Essence", category: "Sunscreen", description: "A hydrating sunscreen enriched with Aloe Vera. Ideal for dry skin to prevent moisture loss while shielding against harmful UV rays.", skinType: "dry", price: 58, imageUrl: "https://i.postimg.cc/5NWV4tK5/Whats-App-Image-2026-06-01-at-20-01-15-(2).jpg", stock: 50 },
    { name: "Soothing Sensitive Mineral SPF", category: "Sunscreen", description: "A 100% mineral-based sunscreen. Gentle on reactive skin, it calms irritation while offering reliable protection against sun damage.", skinType: "sensitive", price: 60, imageUrl: "https://i.postimg.cc/5yFRcwWn/Whats-App-Image-2026-06-01-at-20-01-15-(1).jpg", stock: 50 },
    { name: "Anti-Aging Protection Cream SPF 50", category: "Sunscreen", description: "A nourishing sunscreen with added antioxidants to combat premature aging. Firms and protects mature skin from sun-induced fine lines.", skinType: "mature", price: 65, imageUrl: "https://i.postimg.cc/QMbDPqxS/Whats-App-Image-2026-06-01-at-20-01-15.jpg", stock: 50 }
  ]);
  console.log('✅ Products seeded');

  await sequelize.close();
  console.log('🎉 Done!');
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
